######################################################################
# Automatically generated by qmake (2.01a) Tue Nov 14 12:06:14 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += /ad/eng/users/v/h/vherzog/Desktop/Fall-2017/Labs/Lab5_ec535/blue_screen/. \
               .

# Input
SOURCES += main.cpp
