######################################################################
# Automatically generated by qmake (2.01a) Wed Nov 29 13:31:54 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += /ad/eng/users/v/h/vherzog/Desktop/embedded-christmas-ornament/qt/. \
               .

# Input
SOURCES += main.cpp
